services:
  soter: 
    image: linkaform/nginx:base
    container_name: soter
    build: 
      context: ./ 
      dockerfile: Dockerfile

    volumes:
      # - ./:/srv
      - ./src:/srv/src/
      - ./public:/srv/public/
      - ./cache:/srv/cache/
    ports:
      - "3000:3000"
    stdin_open: true
    command: yarn dev
    tty: true
